qustions={'q1':'what is your favorite food?',
'q2':'what is your favorite color?',
'q3':'what is your favorite team?',
'q4':'what is your favorite college?',
'q5':'what is your favorit car?',
'q6':'what is your favorite foootball player?',
'q7':'what is your favorite volleyball player?',
'q8':'what is your favorite sports?',
'q9':'what is your favorite phone?',
'q10':'what is your favorite animals?',
'q11':'what is your favorite house?',
'q12':'what is your favorite basketballplayer?',
'q13':'what is your favorite flower?',
'q14':'what is your favorite film?',
'q15':'what is your favorite music?',
'q16':'what is your favorite singer?',
'q17':'what is your favorite job?',
'q18':'what is your favorite city?',
'q19':'what is yourr favorite country?',
'q20':'what is your favorite continet?',
}
